# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/controls/service/DAQ/v1/DAQ.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/controls/service/DAQ/v1/DAQ.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from pacsys._proto.controls.common.v1 import device_pb2 as proto_dot_controls_dot_common_dot_v1_dot_device__pb2
from pacsys._proto.controls.common.v1 import status_pb2 as proto_dot_controls_dot_common_dot_v1_dot_status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'proto/controls/service/DAQ/v1/DAQ.proto\x12\x0cservices.daq\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%proto/controls/common/v1/device.proto\x1a%proto/controls/common/v1/status.proto\"\x1a\n\x0bReadingList\x12\x0b\n\x03\x64rf\x18\x01 \x03(\t\"\x87\x01\n\x07Reading\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.common.device.Value\x12)\n\x06status\x18\x03 \x01(\x0b\x32\x15.common.status.StatusB\x02\x18\x01\"2\n\x08Readings\x12&\n\x07reading\x18\x02 \x03(\x0b\x32\x15.services.daq.Reading\"{\n\x0cReadingReply\x12\r\n\x05index\x18\x01 \x01(\r\x12*\n\x08readings\x18\x02 \x01(\x0b\x32\x16.services.daq.ReadingsH\x00\x12\'\n\x06status\x18\x03 \x01(\x0b\x32\x15.common.status.StatusH\x00\x42\x07\n\x05value\">\n\x07Setting\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.common.device.Value\"5\n\x0bSettingList\x12&\n\x07setting\x18\x01 \x03(\x0b\x32\x15.services.daq.Setting\"5\n\x0cSettingReply\x12%\n\x06status\x18\x02 \x03(\x0b\x32\x15.common.status.Status2\x88\x01\n\x03\x44\x41Q\x12\x41\n\x04Read\x12\x19.services.daq.ReadingList\x1a\x1a.services.daq.ReadingReply\"\x00\x30\x01\x12>\n\x03Set\x12\x19.services.daq.SettingList\x1a\x1a.services.daq.SettingReply\"\x00\x42\x32\n$gov.fnal.controls.service.proto.grpcB\x08\x44\x41QProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pacsys._proto.controls.service.DAQ.v1.DAQ_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$gov.fnal.controls.service.proto.grpcB\010DAQProtoP\000'
  _globals['_READING'].fields_by_name['status']._loaded_options = None
  _globals['_READING'].fields_by_name['status']._serialized_options = b'\030\001'
  _globals['_READINGLIST']._serialized_start=168
  _globals['_READINGLIST']._serialized_end=194
  _globals['_READING']._serialized_start=197
  _globals['_READING']._serialized_end=332
  _globals['_READINGS']._serialized_start=334
  _globals['_READINGS']._serialized_end=384
  _globals['_READINGREPLY']._serialized_start=386
  _globals['_READINGREPLY']._serialized_end=509
  _globals['_SETTING']._serialized_start=511
  _globals['_SETTING']._serialized_end=573
  _globals['_SETTINGLIST']._serialized_start=575
  _globals['_SETTINGLIST']._serialized_end=628
  _globals['_SETTINGREPLY']._serialized_start=630
  _globals['_SETTINGREPLY']._serialized_end=683
  _globals['_DAQ']._serialized_start=686
  _globals['_DAQ']._serialized_end=822
# @@protoc_insertion_point(module_scope)
