# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/controls/common/v1/device.proto
# Protobuf Python Version: 6.31.1 (gencode lowered to 6.30.0 - APIs are stable across 6.x)
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'proto/controls/common/v1/device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%proto/controls/common/v1/device.proto\x12\rcommon.device\"\xd2\x06\n\x05Value\x12\x10\n\x06scalar\x18\x01 \x01(\x01H\x00\x12\x35\n\tscalarArr\x18\x02 \x01(\x0b\x32 .common.device.Value.ScalarArrayH\x00\x12\r\n\x03raw\x18\x03 \x01(\x0cH\x00\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\x31\n\x07textArr\x18\x05 \x01(\x0b\x32\x1e.common.device.Value.TextArrayH\x00\x12\x34\n\x08\x61naAlarm\x18\x06 \x01(\x0b\x32 .common.device.Value.AnalogAlarmH\x00\x12\x35\n\x08\x64igAlarm\x18\x07 \x01(\x0b\x32!.common.device.Value.DigitalAlarmH\x00\x12\x37\n\x0b\x62\x61sicStatus\x18\x08 \x01(\x0b\x32 .common.device.Value.BasicStatusH\x00\x1a\x1c\n\x0bScalarArray\x12\r\n\x05value\x18\x01 \x03(\x01\x1a\x1a\n\tTextArray\x12\r\n\x05value\x18\x01 \x03(\t\x1a\xa5\x01\n\x0b\x41nalogAlarm\x12\x0f\n\x07minimum\x18\x01 \x01(\x01\x12\x0f\n\x07maximum\x18\x02 \x01(\x01\x12\x13\n\x0b\x61larmEnable\x18\x03 \x01(\x08\x12\x13\n\x0b\x61larmStatus\x18\x04 \x01(\x08\x12\r\n\x05\x61\x62ort\x18\x05 \x01(\x08\x12\x14\n\x0c\x61\x62ortInhibit\x18\x06 \x01(\x08\x12\x13\n\x0btriesNeeded\x18\x07 \x01(\r\x12\x10\n\x08triesNow\x18\x08 \x01(\r\x1a\xa3\x01\n\x0c\x44igitalAlarm\x12\x0f\n\x07nominal\x18\x01 \x01(\x05\x12\x0c\n\x04mask\x18\x02 \x01(\r\x12\x13\n\x0b\x61larmEnable\x18\x03 \x01(\x08\x12\x13\n\x0b\x61larmStatus\x18\x04 \x01(\x08\x12\r\n\x05\x61\x62ort\x18\x05 \x01(\x08\x12\x14\n\x0c\x61\x62ortInhibit\x18\x06 \x01(\x08\x12\x13\n\x0btriesNeeded\x18\x07 \x01(\r\x12\x10\n\x08triesNow\x18\x08 \x01(\r\x1aw\n\x0b\x42\x61sicStatus\x12:\n\x05value\x18\x01 \x03(\x0b\x32+.common.device.Value.BasicStatus.ValueEntry\x1a,\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x07\n\x05valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pacsys._proto.controls.common.v1.device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALUE_BASICSTATUS_VALUEENTRY']._loaded_options = None
  _globals['_VALUE_BASICSTATUS_VALUEENTRY']._serialized_options = b'8\001'
  _globals['_VALUE']._serialized_start=57
  _globals['_VALUE']._serialized_end=907
  _globals['_VALUE_SCALARARRAY']._serialized_start=387
  _globals['_VALUE_SCALARARRAY']._serialized_end=415
  _globals['_VALUE_TEXTARRAY']._serialized_start=417
  _globals['_VALUE_TEXTARRAY']._serialized_end=443
  _globals['_VALUE_ANALOGALARM']._serialized_start=446
  _globals['_VALUE_ANALOGALARM']._serialized_end=611
  _globals['_VALUE_DIGITALALARM']._serialized_start=614
  _globals['_VALUE_DIGITALALARM']._serialized_end=777
  _globals['_VALUE_BASICSTATUS']._serialized_start=779
  _globals['_VALUE_BASICSTATUS']._serialized_end=898
  _globals['_VALUE_BASICSTATUS_VALUEENTRY']._serialized_start=854
  _globals['_VALUE_BASICSTATUS_VALUEENTRY']._serialized_end=898
# @@protoc_insertion_point(module_scope)
